#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

for var in $@
do
    java -jar wacc-39-compiler.jar "$var"
done
rm -rf *.s

exit $?

