#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

for ((i=1; i<${#@}; i+=2))
do
    java -jar wacc-39-compiler.jar "${@:i:1}" "${@:i+1:1}"
done

exit $?

